sudo: false

services:
  - mongodb

env:
  - IMAGE_TAG="$DOCKER_REGISTRY/elixir/dsw-server:latest"

before_script:
  - mongo dsw-server-test --eval 'db.collection.find()'
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY

cache:
  directories:
  - $HOME/.stack
  - $HOME/.stack-work

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  # Configure stack to use the system GHC installation
  - stack config set system-ghc --global true
  - export PATH=/opt/ghc/ghc-8.2.2/bin:$PATH

script:
  - stack --no-terminal --skip-ghc-check test
  - docker pull $IMAGE_TAG
  - docker build --pull --cache-from $IMAGE_TAG -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
