sudo: required

env:
  - IMAGE_TAG="$DOCKER_REGISTRY/elixir/dsw-server:latest"

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY

script:
  - cd scripts
  - ./build-info.sh
  - cd ..

  - docker pull $IMAGE_TAG
  - docker build --pull --cache-from $IMAGE_TAG -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
