name: dsp-server
version: '1.0.0'
synopsis: DSP Server
description: DSP Server
category: Web
author: Vojtech Knaisl <vknaisl@gmail.com>
maintainer: Vojtech Knaisl <vknaisl@gmail.com>
copyright: 2017 Vojtech Knaisl <vknaisl@gmail.com>
license: MIT
license-file: LICENSE.md
homepage: https://github.com/vknaisl/dsp-server
git: git@github.com:vknaisl/dsp-server.git
bug-reports: https://github.com/vknaisl/dsp-server/issues
tested-with: GHC==7.6.* GHC==7.8.*
library:
  source-dirs: src
  dependencies:
  - base ==4.9.1.0
  - aeson ==1.1.2.0 
  - bson ==0.3.2.3
  - bytestring ==0.10.8.1
  - case-insensitive ==1.2.0.10
  - containers ==0.5.7.1
  - data-default ==0.7.1.1
  - http-types ==0.9.1 
  - lens ==4.15.3
  - jwt ==0.7.2
  - mtl ==2.2.1
  - monad-control ==1.0.2.1
  - monad-logger ==0.3.24
  - mongoDB ==2.3.0
  - network ==2.6.3.2
  - persistent ==2.7.0
  - persistent-template ==2.5.2
  - persistent-mongoDB ==2.6.0
  - pwstore-fast ==2.4.4
  - random ==1.1
  - regex-compat ==0.95.1
  - scotty ==0.11.0
  - text ==1.2.2.2
  - time ==1.6.0.1
  - transformers ==0.5.2.0
  - uuid ==1.3.13
  - vector ==0.12.0.1
  - wai ==3.2.1.1
  - wai-extra ==3.0.20.0
  - wai-cors ==0.2.5
  - warp ==3.2.13
  default-extensions: 
    - TemplateHaskell
    - QuasiQuotes
    - OverloadedStrings
    - MultiParamTypeClasses
    - FlexibleContexts
    - GeneralizedNewtypeDeriving
    - GADTs
    - TypeFamilies
    - DeriveGeneric
    - ExtendedDefaultRules
    - RecordWildCards
    - UnicodeSyntax

executables:
  dsp-server:
    main: Main.hs
    source-dirs: app
    dependencies:
    - base
    - dsp-server
tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -Werror
    dependencies:
    - base ==4.9.1.0
    - dsp-server
    - hspec ==2.4.4
    - hspec-expectations-pretty-diff ==0.7.2.4
    - http-types ==0.9.1
    - mtl ==2.2.1
    - persistent ==2.7.0
    - scotty ==0.11.0
    - time ==1.6.0.1
    - wai ==3.2.1.1
    - wai-extra ==3.0.20.0

    
    # - dsp-km-migration-library
    # - lens == 4.15.4
    
    # - HUnit >= 1.3.0.0
    # - text == 1.2.2.2
    # - hspec == 2.4.4
