name: dsp-server
version: '1.0.0'
synopsis: DSP Server
description: DSP Server
category: Web
author: Vojtech Knaisl <vknaisl@gmail.com>
maintainer: Vojtech Knaisl <vknaisl@gmail.com>
copyright: 2017 Vojtech Knaisl <vknaisl@gmail.com>
license: MIT
license-file: LICENSE.md
homepage: https://github.com/vknaisl/dsp-server
git: git@github.com:vknaisl/dsp-server.git
bug-reports: https://github.com/vknaisl/dsp-server/issues
tested-with: GHC==7.6.* GHC==7.8.*
library:
  source-dirs: src
  dependencies:
  - base
  - aeson
  - bson
  - data-default
  - http-types
  - lens
  - mtl
  - monad-control
  - monad-logger
  - mongoDB
  - network
  - persistent
  - persistent-template
  - persistent-mongoDB
  - random
  - scotty
  - text
  - time
  - transformers
  - uuid
  - wai
  - wai-extra
  - warp
  default-extensions: 
    - TemplateHaskell
    - QuasiQuotes
    - OverloadedStrings
    - MultiParamTypeClasses
    - FlexibleContexts
    - GeneralizedNewtypeDeriving
    - GADTs
    - TypeFamilies
    - DeriveGeneric
    - ExtendedDefaultRules
    - RecordWildCards

executables:
  dsp-server:
    main: Main.hs
    source-dirs: app
    dependencies:
    - base
    - dsp-server
tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -Werror
    dependencies:
    - base
    - dsp-server
    - hspec
    - hspec-expectations-pretty-diff
    - http-types
    - mtl
    - persistent
    - scotty
    - time
    - wai
    - wai-extra

    
    # - dsp-km-migration-library
    # - lens == 4.15.4
    
    # - HUnit >= 1.3.0.0
    # - text == 1.2.2.2
    # - hspec == 2.4.4
