name: dsp-server
version: '1.0.0'
synopsis: DSP Server
description: DSP Server
category: Web
author: Vojtech Knaisl <vknaisl@gmail.com>
maintainer: Vojtech Knaisl <vknaisl@gmail.com>
copyright: 2017 Vojtech Knaisl <vknaisl@gmail.com>
license: MIT
license-file: LICENSE.md
homepage: https://github.com/vknaisl/dsp-server
git: git@github.com:vknaisl/dsp-server.git
bug-reports: https://github.com/vknaisl/dsp-server/issues
tested-with: GHC==7.6.* GHC==7.8.*
library:
  source-dirs: src
  dependencies:
  - base ==4.*
  - aeson >=0.7 && <0.12
  - bson ==0.3.2.3
  - bson-generic ==0.0.*
  - data-default ==0.5.*
  - http-types ==0.9.*
  - lens ==4.13
  - mtl ==2.*
  - monad-control ==1.0.1.0
  - monad-logger ==0.3.*
  - mongoDB ==2.0.10
  - network ==2.*
  - persistent ==2.*
  - persistent-template ==2.*
  - persistent-mongoDB ==2.6.0
  - random ==1.1
  - scotty ==0.11.*
  - text ==1.2.1.3
  - time ==1.*
  - transformers >=0.3 && <0.5
  - uuid ==1.3.12
  - wai ==3.2.*
  - wai-extra ==3.0.*
  - warp ==3.*
  default-extensions: 
    - TemplateHaskell
    - QuasiQuotes
    - OverloadedStrings
    - MultiParamTypeClasses
    - FlexibleContexts
    - GeneralizedNewtypeDeriving
    - GADTs
    - TypeFamilies
    - DeriveGeneric
    - ExtendedDefaultRules
    - RecordWildCards

executables:
  dsp-server:
    main: Main.hs
    source-dirs: app
    dependencies:
    - base
    - dsp-server
tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -Werror
    dependencies:
    - base >=4.7 && <5
    - dsp-server
    - hspec >=1 && <3
    - hspec-expectations-pretty-diff == 0.7.2.4
    - http-types
    - mtl
    - persistent
    - scotty
    - time
    - wai
    - wai-extra

    
    # - dsp-km-migration-library
    # - lens == 4.15.4
    
    # - HUnit >= 1.3.0.0
    # - text == 1.2.2.2
    # - hspec == 2.4.4
