name: src
version: '1.0.0'
synopsis: DSP Server
description: DSP Server
category: Web
author: Vojtech Knaisl <vknaisl@gmail.com>
maintainer: Vojtech Knaisl <vknaisl@gmail.com>
copyright: 2017 Vojtech Knaisl <vknaisl@gmail.com>
license: MIT
license-file: LICENSE.md
homepage: https://github.com/vknaisl/dsp-server
git: git@github.com:vknaisl/dsp-server.git
bug-reports: https://github.com/vknaisl/dsp-server/issues
tested-with: GHC==7.6.* GHC==7.8.*
data-files:
  - config/app-config.cfg
  - config/build-info.cfg
library:
  source-dirs: lib
  dependencies:
  - base
  - aeson
  - bson
  - bytestring
  - case-insensitive
  - ConfigFile
  - containers
  - data-default
  - http-types
  - lens
  - jwt
  - mtl
  - monad-control
  - monad-logger
  - mongoDB
  - network
  - persistent
  - persistent-template
  - persistent-mongoDB
  - pretty-simple
  - pwstore-fast
  - random
  - regex-compat
  - scotty
  - text
  - time
  - transformers
  - uuid
  - vector
  - wai
  - wai-extra
  - wai-cors
  - warp
  default-extensions:
    - TemplateHaskell
    - QuasiQuotes
    - OverloadedStrings
    - MultiParamTypeClasses
    - FlexibleContexts
    - GeneralizedNewtypeDeriving
    - GADTs
    - TypeFamilies
    - DeriveGeneric
    - ExtendedDefaultRules
    - RecordWildCards
    - UnicodeSyntax
    - ExistentialQuantification

executables:
  dsp-server:
    main: Main.hs
    source-dirs: app
    dependencies:
    - base
    - src
tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - aeson
    - bson
    - bytestring
    - case-insensitive
    - ConfigFile
    - containers
    - data-default
    - http-types
    - lens
    - jwt
    - mtl
    - monad-control
    - monad-logger
    - mongoDB
    - network
    - persistent
    - persistent-template
    - persistent-mongoDB
    - pretty-simple
    - pwstore-fast
    - random
    - regex-compat
    - scotty
    - text
    - time
    - transformers
    - uuid
    - vector
    - wai
    - wai-extra
    - wai-cors
    - warp
    - src
    - hspec
    - hspec-expectations-pretty-diff
    - hspec-wai
    - hspec-wai-json
    default-extensions:
      - TemplateHaskell
      - QuasiQuotes
      - OverloadedStrings
      - MultiParamTypeClasses
      - FlexibleContexts
      - GeneralizedNewtypeDeriving
      - GADTs
      - TypeFamilies
      - DeriveGeneric
      - ExtendedDefaultRules
      - RecordWildCards
      - UnicodeSyntax
      - ExistentialQuantification
