extra-deps:
- aeson-0.11.3.0
- base-compat-0.9.3
- base-orphans-0.6
- bson-generic-0.0.8.1
- bifunctors-5.4.2
- bytestring-builder-0.10.8.1.0
- call-stack-0.1.0
- fast-logger-2.4.10
- hspec-2.4.4
- hspec-core-2.4.4
- hspec-discover-2.4.4
- hspec-expectations-0.8.2
- mmorph-1.1.0
- persistent-2.7.0
- persistent-template-2.5.3
- persistent-mongoDB-2.6.0
- quickcheck-io-0.2.0
- text-1.2.1.3
- transformers-compat-0.5.1.4
- unix-compat-0.4.3.1
- unix-time-0.3.7
- wai-extra-3.0.20.0
- warp-3.2.13
install-ghc: true
require-stack-version: ! '>=1.0.4'
resolver: lts-6.9
flags:
  text:
    integer-simple: false
